
### GET all Clientes
GET http://localhost:3000/api/clientes

### POST a Cliente
# @name createCliente
POST http://localhost:3000/api/clientes
Content-Type: application/json

{
  "nombre": "Gerardo",
  "apellido": "Garcia",
  "tipoDocumento": "DNI",
  "documento": 12345,
  "telefono": "5678",
  "email": "gerardo@gmail.com",
  "password": "gerardito",
  "licenciaConducir": "B456AJK"
}

### ID
@id = {{createCliente.response.body.data.idCliente}}

### GET one Cliente
GET http://localhost:3000/api/clientes/{{id}}

### PUT a Cliente (reemplaza todos los campos)
PUT http://localhost:3000/api/clientes/{{id}}
Content-Type: application/json

{
  "nombre": "Olivo",
  "apellido": "Garcia",
  "tipoDocumento": "DNI",
  "documento": 54321,
  "telefono": "9999",
  "email": "olivo@gmail.com",
  "password": "olivito",
  "licenciaConducir": "C123XYZ"
}

### PATCH a Cliente (actualización parcial)
PATCH http://localhost:3000/api/clientes/{{id}}
Content-Type: application/json

{
  "nombre": "Pedro",
  "apellido": "Gonzales"
}

### DELETE a Cliente
DELETE http://localhost:3000/api/clientes/{{id}}
